# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Q4Solutions' do

end

target 'Q4SolutionsTests' do

end

pod 'Google/Analytics'